# Generated by Django 2.2.4 on 2019-08-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('cover', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('published', models.DateTimeField(null=True)),
                ('publisher', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pages', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('website', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
